import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {makePlayer,publicRoom,act} from '../engine.mjs';
import {presetDeck} from '../public/deck-rules.js';
const cards=JSON.parse(fs.readFileSync(new URL('../public/cards.json',import.meta.url)));
test('Manual playmat protects hidden cards, ownership and stale moves; preserves cards',()=>{
 const players=['A','B'].map(n=>makePlayer(n,presetDeck('SD01',cards).entries,cards));
 const r={players,version:1,turn:1,active:0,status:'playing',log:[]};
 const send=(seat,cmd)=>act(r,players[seat].token,{version:r.version,...cmd},cards);
 const code=players[0].hand[0];
 send(0,{type:'tablePlace',index:0,code,zone:'action',x:.2,y:.8,faceDown:true});
 const id=players[0].table[0].id;
 assert.equal(publicRoom(r,players[1].token).players[0].table[0].code,null);
 assert.equal(publicRoom(r,players[0].token).players[0].table[0].code,code);
 assert.ok(!r.log[0].text.includes(cards.find(c=>c.code===code).name));
 assert.throws(()=>send(1,{type:'tableFlip',id}));
 assert.throws(()=>send(0,{type:'tableMove',id,zone:'concerto',x:2,y:0}));
 assert.throws(()=>send(0,{type:'tableFlip',id,version:1}));
 send(0,{type:'tableMove',id,zone:'concerto',x:1,y:0});
 send(0,{type:'tableFlip',id});
 assert.equal(publicRoom(r,players[1].token).players[0].table[0].code,code);
 send(0,{type:'tableTake',id,to:'hand'});
 assert.equal(players[0].table.length,0);assert.equal(players[0].hand.length+players[0].deck.length,40);
 delete players[0].table;
 send(0,{type:'tablePlace',index:0,code:players[0].hand[0],zone:'action',x:0,y:0,faceDown:false});
 send(0,{type:'clear'});
 assert.equal(players[0].table.length,0);assert.equal(players[0].hand.length+players[0].deck.length+players[0].trash.length,40);
});
